language: objective-c
osx_image: xcode9.2
podfile: ./Podfile

env:
  global:
    - SCHEME="setup-project"
    - PROJECT="setup-project"
    - WORKSPACE="$PROJECT.xcworkspace"

install:
  - set -o pipefail
  - ./scripts/install

script:
  - ./scripts/branch
  - ./scripts/linter
  - fastlane beta
