language: objective-c
osx_image: xcode9.2
podfile: ./Podfile

env:
  global:
    - PROJECT="setup-project"
    - SCHEME="setup-project"
    - WORKSPACE="$PROJECT.xcworkspace"

install:
  ./scripts/install

script:
  - ./scripts/branch
  - xcodebuild -sdk iphonesimulator -workspace $WORKSPACE -scheme $SCHEME
